# Generated by Django 5.1.6 on 2025-02-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Punto2Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_archivo', models.CharField(default='Sin Nombre', max_length=200)),
                ('Numero_paginas', models.IntegerField(default=0)),
                ('CUFE', models.TextField(blank=True, default='SIN_CUFE', null=True)),
                ('Peso_archivo', models.FloatField(default=0.1)),
            ],
        ),
    ]
